version: '2'
services:
  bitcoind:
    build: .
    networks:
      - btcnet
    volumes:
      - bitcoind-data:/bitcoin
    env_file:
      - bitcoin.conf.env
    ports:
      - "8333:8333"
      - "8332:8332"
    container_name: bitcoind
    restart: on-failure
volumes:
  bitcoind-data:
networks:
  btcnet: