version: '2'
services:
  bitcoind:
    build: .
    volumes:
      - bitcoind-data:/bitcoin
    ports:
      - "8333:8333"
      - "8332:8332"
    container_name: bitcoind
    restart: always
volumes:
  bitcoind-data:
